insert into studenti (nome, cognome) value ('yousef', 'abdelmoneim ');
insert into studenti (nome, cognome) value ('Francesco', 'Agosta ');
insert into studenti (nome, cognome) value ('Janice', 'Brun ');
insert into studenti (nome, cognome) value ('Roberto', 'Cantore ');
insert into studenti (nome, cognome) value ('Emanuele', 'Carruba ');
insert into studenti (nome, cognome) value ('Farouq', 'Chemmam ');
insert into studenti (nome, cognome) value ('Andrea', 'Cianchini ');
insert into studenti (nome, cognome) value ('Cristian', 'Cioban ');
insert into studenti (nome, cognome) value ('Ivan', 'Cioffi ');
insert into studenti (nome, cognome) value ('Umberto', 'Farabini ');
insert into studenti (nome, cognome) value ('Federico', 'Freccia ');
insert into studenti (nome, cognome) value ('Riccardo', 'Gouthier ');
insert into studenti (nome, cognome) value ('Sara', 'Ingrassia ');
insert into studenti (nome, cognome) value ('Rebecca', 'Maurutto ');
insert into studenti (nome, cognome) value ('Mikael', 'Mbiada Nganou ');
insert into studenti (nome, cognome) value ('Matteo', 'Ninotti ');
insert into studenti (nome, cognome) value ('Matteo', 'Piana ');
insert into studenti (nome, cognome) value ('Pietro', 'Picchiottino ');
insert into studenti (nome, cognome) value ('Federico', 'Podio ');
insert into studenti (nome, cognome) value ('Andrea', 'Polito ');
insert into studenti (nome, cognome) value ('Tommaso', 'Salza ');
insert into studenti (nome, cognome) value ('Gian Marco', 'Silvano ');
insert into studenti (nome, cognome) value ('Cristian', 'Torres ');
insert into studenti (nome, cognome) value ('Alessandro', 'Verduna ');
insert into studenti (nome, cognome) value ('David', 'Zolfaroli ');
insert into studenti (nome, cognome) value ('Matteo', 'Pironato ');
insert into studenti (nome, cognome) value ('Allaeldene', 'Ilou ');
insert into studenti (nome, cognome) value ('ESTHER WANJIRU', 'NGUMO');
